config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'messages#index'

  resources :users, only: [ :index, :show ]
  resources :messages, only: [:index, :new, :create, :destroy]

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user

  validates :user, presence: true
  validates :content, presence: true, length: { minimum: 2, maximum: 140 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  login                  :string           not null
#  email                  :string           not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#

class User < ActiveRecord::Base
  attr_accessor :virtual_login

  has_many :messages

  has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:virtual_login)
      where(conditions.to_h).where(['LOWER(login) = :value OR LOWER(email) = :value', { :value => login.downcase }]).first
    else
      where(conditions.to_h).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :login
    devise_parameter_sanitizer.for(:sign_up) << :email
    devise_parameter_sanitizer.for(:sign_in) << :virtual_login
    devise_parameter_sanitizer.for(:account_update) << :login << :avatar
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = Message.order('created_at DESC')
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params.merge({ user: current_user }))

    if @message.save
      redirect_to messages_path
    else
      render :new
    end
  end

  def destroy
    @message = Message.find(params[:id])
    if @message.user == current_user
      flash[:success] = 'Message deleted successfully'
      @message.destroy
    else
      flash[:error] = 'You can\'t delete message sent by someone else'
    end
    redirect_to messages_path
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Socialapp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - flash.each do |key, value|
      .alert{ class: "alert-#{key}" }
        %button.close{ data: { dismiss: :alert } } x
        %strong
          = value

    - unless current_user.nil?
      = link_to 'new message', new_message_path
      - unless request.path == edit_user_registration_path
        = link_to 'Profile settings', edit_user_registration_path
        \|
      = link_to 'Log out', destroy_user_session_path, method: :delete
    = yield

app/views/messages/index.html.haml
%h1 Messages

%table
  %thead
    %tr
      %th User
      %th Message
      %th Options

  %tbody
    - @messages.each do |msg|
      %tr
        %td= msg.user.login
        %td= msg.content
        - if msg.user == current_user
          %td= link_to 'X', message_path(msg), method: :delete

app/views/messages/new.html.haml
= form_for @message do |f|
  = f.label :content
  = f.text_field :content
  = f.submit :send

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Avatar
      %th Login
      %th Email
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= image_tag user.avatar.url(:thumb)
        %td= user.login
        %td= user.email
        %td= link_to 'Show', user

app/views/users/show.html.haml
%p#notice= notice

%p
  = image_tag @user.avatar.url(:medium)
%p
  %b Login:
  = @user.login
%p
  %b Email:
  = @user.email

= link_to 'Back', users_path